### PR TITLE
Upgrade base64 0.12 -> 0.13

### PR DESCRIPTION
**Pull request by boxdot**

### CODE REVIEW

**Comment by Narsil** [comment]
Hi @boxdot 

Care to share reasons of why you want to make such a change ?

**Comment by boxdot** [comment]
Hi

Most of the ecosystem moved to base64 v0.13. `spm_precompiled` is the only dependency in our (quite big) tree using v0.12. Between both version the minimum required rust version 1.34.0. did not change, so I thought it might be worth it upgrading the dependency.

I understand if you have your reasons not to upgrade though.

**Comment by Narsil** [comment]
@boxdot no issues at all, I guessed it must have been something like this. 

I superseeded with another PR with you as co-author which also includes other updates + clippy warnings fixes .
https://github.com/huggingface/spm_precompiled/pull/2

**Comment by Narsil** [comment]
Superseeded by #2

**Pull request closed without merging**
